# make_percell_violin_v04_2026-09-21.py
# ED8 v04: layout rework - unified box+strip style (median/IQR box/10-90% whiskers + all scatter points),
# per-row width allocated by group count (f/i widened), annotations wrapped (fixes the v03 right-side blank).
# Data identical to v03: master table + drug-arm table (361 rows, regenerated by this script as well).
import os, sys, json
import numpy as np
import pandas as pd
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle
from pathlib import Path

ROOT = os.path.dirname(os.path.abspath(__file__))
LINE = os.path.dirname(ROOT)
RES = os.path.join(LINE, "结果")
AM = os.path.join(LINE, "α模型")
FIGD = os.path.join(ROOT, "figures_v01")
os.makedirs(FIGD, exist_ok=True)

sys.path.insert(0, str(Path(sys.executable).parent.parent.parent))
try:
    from daimon_runtime import setup_plot
    setup_plot()
except Exception:
    pass
plt.rcParams.update({"font.size": 7, "axes.linewidth": 0.6,
                     "xtick.major.width": 0.6, "ytick.major.width": 0.6})

df = pd.read_csv(os.path.join(RES, "逐细胞参数总表_四通道_2026-09-21.csv"))
df = df[df["ok"] == 1]

def L(channel, param, voltage=None, group=None, temp=None, dataset=None):
    d = df[(df.channel == channel) & (df.parameter == param)]
    if voltage is not None:
        d = d[d.voltage_mV == voltage]
    if group is not None:
        d = d[d.group == group]
    if temp is not None:
        d = d[d.temp_C.astype(str) == str(temp)]
    if dataset is not None:
        d = d[d.dataset == dataset]
    return d["value"].to_numpy(float)

# ============ 1) drug-arm long table (same as v03, idempotently regenerated) ============
arm_rows = []
ik = pd.read_csv(os.path.join(AM, "2026-09-15_Kα药_IKs药物表分解判决_逐文件表_结果.csv"))
for _, r in ik.iterrows():
    for param, val, unit in [("V_half_act_drug", r.vh, "mV"), ("k_act_drug", r.k, "mV")]:
        arm_rows.append(["IKs", "Chan2023-Zenodo8226585", f"{r.arm}药臂", 22, r.file,
                         param, np.nan, val, unit, 1, f"drug-treated ({r.arm}); G-V R2={r.gv_r2:.3f}"])
kj = json.load(open(os.path.join(AM, "2026-09-15_Kα药_IKs药物表分解判决_结果.json"), encoding="utf-8"))
for f, v in kj["hmr"].items():
    for param, val, unit in [("V_half_act_drug", v["gv"][0], "mV"), ("k_act_drug", v["gv"][1], "mV")]:
        arm_rows.append(["IKs", "Chan2023-Zenodo8226585", "HMR减除臂", 22, f,
                         param, np.nan, val, unit, 1, f"HMR-1556 subtraction; G-V R2={v['gv'][2]:.3f}"])
c1 = json.load(open(os.path.join(AM, "2026-09-15_Cα1b_CaV12失活电荷载子判决_17mV段_结果.json"), encoding="utf-8"))
for carrier, cells in c1["verdict"]["f_inact_cells"].items():
    for f, val in cells.items():
        arm_rows.append(["CaV1.2", "Ren2022-g3msb", f"表征对照_{carrier}", "31-37", f,
                         "f_inact", 17.0, val, "frac", 1, "characterization-batch control (Cα1b)"])
c5 = json.load(open(os.path.join(AM, "2026-09-15_Cα5_CaV12药物形状调制判决_结果.json"), encoding="utf-8"))
for c in c5["cells"]:
    t = round(c["T_med"]) if c.get("T_med") else ""
    if c.get("f_ctrl") is not None:
        arm_rows.append(["CaV1.2", "Ren2022-g3msb", c["group"], t, c["file"],
                         "f_inact", 17.0, c["f_ctrl"], "frac", 1, "pre-drug control segment (Cα5)"])
    if c.get("f_drug") is not None:
        arm_rows.append(["CaV1.2", "Ren2022-g3msb", c["group"], t, c["file"],
                         "f_inact_drug", 17.0, c["f_drug"], "frac", 1, "drug segment (Cα5)"])
nv = pd.read_csv(os.path.join(AM, "2026-09-15_Nα药_Nav15药物形状调制判决_逐条件表_结果.csv"))
for _, r in nv.iterrows():
    arm_rows.append(["Nav1.5", "Tarasov2026-Dryad", f"{r.drug}药臂", "", r.file_id,
                     "f_block_step", np.nan, r.f_step, "frac", 1,
                     f"drug-treated; conc {r.conc_uM} uM; group {r.group}"])
arm = pd.DataFrame(arm_rows, columns=["channel", "dataset", "group", "temp_C", "cell_id",
                                      "parameter", "voltage_mV", "value", "unit", "ok", "note"])
arm.to_csv(os.path.join(RES, "逐细胞参数总表_加药臂_2026-09-21.csv"), index=False, encoding="utf-8-sig")

def A(channel, param, group):
    d = arm[(arm.channel == channel) & (arm.parameter == param) & (arm.group == group)]
    return d["value"].to_numpy(float)

# ============ 2) unified box+strip plotting ============
def box_strip(ax, d, x, color, w=0.52):
    d = np.asarray(d, float)
    d = d[np.isfinite(d)]
    n = len(d)
    if n == 0:
        return
    xj = x + np.random.default_rng(7).uniform(-0.15, 0.15, n)
    ax.scatter(xj, d, s=2.6, c="k", alpha=0.38, linewidths=0, zorder=3)
    med = np.median(d)
    if n >= 5:
        q1, q3 = np.percentile(d, [25, 75])
        p10, p90 = np.percentile(d, [10, 90])
        ax.add_patch(Rectangle((x - w / 2, q1), w, q3 - q1, facecolor=color,
                               alpha=0.20, edgecolor=color, lw=0.9, zorder=2))
        ax.plot([x, x], [p10, q1], color=color, lw=0.9, zorder=2)
        ax.plot([x, x], [q3, p90], color=color, lw=0.9, zorder=2)
        ax.plot([x - 0.12, x + 0.12], [p10, p10], color=color, lw=0.9, zorder=2)
        ax.plot([x - 0.12, x + 0.12], [p90, p90], color=color, lw=0.9, zorder=2)
        ax.plot([x - w / 2, x + w / 2], [med, med], color=color, lw=2.0, zorder=4)
    else:
        ax.plot([x - 0.26, x + 0.26], [med, med], color=color, lw=1.8, zorder=4)

def panel(ax, data_list, labels, color, tick_fs=6.0, rot=0, counts=True):
    pos = np.arange(1, len(data_list) + 1)
    for i, d in enumerate(data_list):
        box_strip(ax, d, pos[i], color)
    ax.set_xticks(pos)
    labs = labels
    if counts:
        labs = ["{}\n({})".format(l, np.isfinite(np.asarray(d, float)).sum())
                for l, d in zip(labels, data_list)]
    if rot:
        ax.set_xticklabels(labs, fontsize=tick_fs, rotation=rot, ha="right")
    else:
        ax.set_xticklabels(labs, fontsize=tick_fs)
    ax.spines[["top", "right"]].set_visible(False)

fig = plt.figure(figsize=(7.2, 7.5))
gs = fig.add_gridspec(3, 1, height_ratios=[1, 1, 1], hspace=0.62,
                      left=0.09, right=0.99, top=0.945, bottom=0.105)
r1 = gs[0].subgridspec(1, 3, width_ratios=[1, 1, 1], wspace=0.45)
r2 = gs[1].subgridspec(1, 3, width_ratios=[1.0, 1.05, 1.6], wspace=0.45)
r3 = gs[2].subgridspec(1, 3, width_ratios=[0.95, 1.15, 1.7], wspace=0.50)
axes = [fig.add_subplot(r1[i]) for i in range(3)] + \
       [fig.add_subplot(r2[i]) for i in range(3)] + \
       [fig.add_subplot(r3[i]) for i in range(3)]

TEMPS = [25, 27, 30, 33, 37]

# a: hERG E_rev × T
ax = axes[0]
panel(ax, [L("hERG", "E_rev", temp=t) for t in TEMPS], [str(t) for t in TEMPS],
      "#4C72B0", tick_fs=6.0)
ax.scatter([5.0], [-92.9], marker="*", s=60, c="#B22222", zorder=6)
ax.text(0.03, 0.04, "★ model62-chain fit −92.9", transform=ax.transAxes,
        fontsize=5.5, color="#B22222", va="bottom")
ax.set_ylabel("per-cell $E_{rev}$ (mV)")
ax.set_xlabel("temperature (°C)")
ax.set_title("hERG · Lei CHO 670 wells", fontsize=7)

# b: hERG h_ss limb 25 °C
ax = axes[1]
panel(ax, [L("hERG", "h_ss", voltage=v, temp=25) for v in [-140, -120, -100]],
      ["−140", "−120", "−100"], "#4C72B0")
ax.set_ylabel("per-cell $h_{ss}$")
ax.set_xlabel("voltage (mV)")
ax.set_title("hERG · $h_{ss}$ negative limb, 25 °C", fontsize=7)

# c: hERG τ_rec(−120) × T
ax = axes[2]
panel(ax, [L("hERG", "tau_rec", voltage=-120, temp=t) for t in TEMPS],
      [str(t) for t in TEMPS], "#4C72B0", tick_fs=6.0)
ax.scatter([5.0], [3.04], marker="*", s=60, c="#B22222", zorder=6)
ax.text(0.97, 0.97, "★ Beattie HEK 3.04 ms", transform=ax.transAxes,
        fontsize=5.5, color="#B22222", va="top", ha="right")
ax.set_ylabel(r"per-cell $\tau_{rec}$(−120 mV) (ms)")
ax.set_xlabel("temperature (°C)")
ax.set_ylim(0, 18)
ax.set_yticks([0, 3, 6, 9, 12, 15, 18])
ax.set_title("hERG · $\tau_{rec}$ travels: $Q_{10}$=2.84, $R^2$=0.991", fontsize=7)

# d: Nav τ(−40) by modality
ax = axes[3]
d1 = L("Nav1.5", "tau_decay", group="多通道膜片")
d2 = L("Nav1.5", "tau_decay", group="单通道膜片")
d3 = L("Nav1.5", "tau_h", voltage=-40.0, dataset="Nα2-Lei-Nav35")
box_strip(ax, d1, 1, "#DD8452")
box_strip(ax, d2, 2, "#DD8452")
xj = 3 + np.random.default_rng(7).uniform(-0.15, 0.15, len(d3))
ax.scatter(xj, d3, marker="D", s=13, c="#B22222", alpha=0.9, zorder=3)
ax.plot([3 - 0.26, 3 + 0.26], [np.median(d3)] * 2, color="#DD8452", lw=1.8, zorder=4)
ax.set_xticks([1, 2, 3])
ax.set_xticklabels([f"multi\nch\n({len(d1)})", f"single\nch\n({len(d2)})",
                    f"whole\ncell\n({len(d3)})"], fontsize=5.8)
cv1 = np.std(d1) / np.mean(d1)
ax.set_ylim(0, 7.5)
ax.set_title(f"Nav1.5 · τ(−40 mV): distribution (CV={cv1:.2f})", fontsize=6.2)
ax.set_ylabel("per-patch τ (ms)")
ax.set_xlabel("recording modality")
ax.spines[["top", "right"]].set_visible(False)

# e: Nav drug-arm dose-effect
ax = axes[4]
drugs = ["Naltrexone", "Methadone", "Naloxone", "Buprenorphine", "Norbuprenorphine"]
cmap = plt.get_cmap("tab10")
for j, dr in enumerate(drugs):
    sub = nv[nv.drug == dr]
    ax.scatter(sub.conc_uM, sub.f_step, s=9, color=cmap(j), alpha=0.75,
               linewidths=0, label=f"{dr} ({len(sub)})")
ax.axhline(0, lw=0.7, color="0.4", zorder=1)
ax.set_xscale("log")
ax.set_xlabel("drug concentration (µM)")
ax.set_ylabel("fractional block of step $I_{Na}$")
ax.set_title("Nav1.5 · drug arm: dose-dependent block", fontsize=6.5)
ax.legend(fontsize=4.6, frameon=False, loc="upper left", handletextpad=0.2,
          borderaxespad=0.1, labelspacing=0.25)
ax.spines[["top", "right"]].set_visible(False)

# f: IKs V½ / k —— WT | Mef | DIDS | HMR
ax = axes[5]
wt_v = L("IKs", "V_half_act"); wt_k = L("IKs", "k_act")
mef_v = A("IKs", "V_half_act_drug", "Mef药臂"); mef_k = A("IKs", "k_act_drug", "Mef药臂")
dids_v = A("IKs", "V_half_act_drug", "DIDS药臂"); dids_k = A("IKs", "k_act_drug", "DIDS药臂")
hmr_v = A("IKs", "V_half_act_drug", "HMR减除臂"); hmr_k = A("IKs", "k_act_drug", "HMR减除臂")
all_d = [wt_v, mef_v, dids_v, hmr_v, wt_k, mef_k, dids_k, hmr_k]
pos = [1, 2, 3, 4, 6, 7, 8, 9]
for i, dd in enumerate(all_d):
    box_strip(ax, dd, pos[i], "#55A868")
ax.axvline(5, lw=0.6, color="0.7", ls=":")
ax.set_ylim(-100, 58)
ax.text(2.5, 50, "$V_{1/2}$ act", ha="center", fontsize=6.5)
ax.text(7.5, 50, "$k$ act", ha="center", fontsize=6.5)
ax.set_xticks(pos)
ax.set_xticklabels(["WT", "\nMef", "DIDS", "\nHMR"] * 2, fontsize=5.5)
ax.scatter([0.62], [25.4], marker="*", s=45, c="#B22222", zorder=6)
ax.set_ylabel("mV")
ax.set_title("IKs · WT pool vs drug arms ($V_{1/2}$ & $k$; n = 8/15/26/6)", fontsize=6.2)
ax.spines[["top", "right"]].set_visible(False)

# g: CaV E_chord / Q10
ax = axes[6]
f1 = L("CaV1.2", "E_chord")
panel(ax, [f1], ["$E_{chord}$"], "#8172B3", tick_fs=6.5)
ax.axhline(46, ls="--", lw=0.9, color="#B22222", zorder=2)
ax.text(0.66, 41.5, "literature anchor +46 mV", fontsize=5.5, color="#B22222")
ax.set_ylabel("mV")
ax.set_ylim(28, 66)
ax2 = ax.twinx()
f2 = L("CaV1.2", "Q10_tau_slow")
xj = 2 + np.random.default_rng(7).uniform(-0.10, 0.10, len(f2))
ax2.scatter(xj, f2, s=11, c="#4a3d6b", alpha=0.85, linewidths=0)
ax2.plot([2 - 0.26, 2 + 0.26], [np.median(f2)] * 2, color="#8172B3", lw=1.8, zorder=4)
ax2.set_ylabel(r"$Q_{10}(\tau_{slow})$", color="#4a3d6b")
ax2.set_ylim(0.5, 2.5)
ax2.spines["top"].set_visible(False)
ax.set_xticks([1, 2])
ax.set_xticklabels([f"$E_{{chord}}$\n({len(f1)})", f"$Q_{{10}}$($\\tau_{{slow}}$)\n({len(f2)})"],
                   fontsize=6.0)
ax.set_title("CaV1.2 · Ren 2022 (Ca$^{2+}$), complete record", fontsize=6.5)

# h: CaV f_inact controls
ax = axes[7]
h1 = A("CaV1.2", "f_inact", "表征对照_Ca2")
h2 = np.concatenate([A("CaV1.2", "f_inact", g) for g in
                     ["Buprenorphine_Ca2+_PT", "Methadone_Ca2+_PT", "Norbuprenorphine_Ca2+_PT",
                      "Verapamil_Ca2+_PT", "Verapamil_Ca2+_RT"]])
h3 = A("CaV1.2", "f_inact", "表征对照_Ba2")
h4 = np.concatenate([A("CaV1.2", "f_inact", g) for g in
                     ["Diltiazem_Ba2+_PT", "Norbuprenorphine_Ba2+_PT", "Naloxone_Ba2+_PT"]])
panel(ax, [h1, h2, h3, h4], ["char.\nCa$^{2+}$", "screen\nCa$^{2+}$",
                             "char.\nBa$^{2+}$", "screen\nBa$^{2+}$"],
      "#8172B3", tick_fs=5.5)
ax.set_ylabel(r"pre-drug $f_{inact}$")
ax.set_ylim(0, 1.05)
ax.set_title("CaV1.2 · pre-drug $f_{inact}$: batch-anchored", fontsize=6.5)

# i: CaV drug effect delta-f per group
ax = axes[8]
groups = ["Buprenorphine_Ca2+_PT", "Methadone_Ca2+_PT", "Norbuprenorphine_Ca2+_PT",
          "Verapamil_Ca2+_PT", "Verapamil_Ca2+_RT",
          "Diltiazem_Ba2+_PT", "Norbuprenorphine_Ba2+_PT", "Naloxone_Ba2+_PT"]
short = ["Bup·Ca", "Meth·Ca", "Norb·Ca", "VeraPT·Ca", "VeraRT·Ca",
         "Dilt·Ba", "Norb·Ba", "Nalo·Ba"]
df_groups = []
for g in groups:
    sub = arm[(arm.group == g)]
    fc = sub[sub.parameter == "f_inact"].set_index("cell_id")["value"]
    fd = sub[sub.parameter == "f_inact_drug"].set_index("cell_id")["value"]
    common = fc.index.intersection(fd.index)
    df_groups.append((fd[common] - fc[common]).to_numpy(float))
panel(ax, df_groups, short, "#8172B3", tick_fs=5.0, rot=45)
ax.axhline(0, lw=0.7, color="0.4", zorder=1)
ax.set_ylabel(r"$\Delta f_{inact}$ (drug − pre-drug)")
ax.set_title("CaV1.2 · drug effect per cell by group", fontsize=6.5)

for i, ax in enumerate(axes):
    ax.text(-0.26, 1.05, "abcdefghi"[i], transform=ax.transAxes,
            fontsize=9, fontweight="bold", va="top")

fig.text(0.09, 0.028,
         "Box summaries (median, IQR, 10–90% whiskers) overlay groups with n ≥ 5; "
         "every cell/patch/condition is shown as a point.",
         fontsize=6, color="0.35")
fig.text(0.09, 0.008,
         "a–d, g: complete QC-passed public record (SI S9). "
         "e, f, h, i: pre-registered pharmacology arms; drug-naïve and drug-treated shown separately (SI S7 arm table).",
         fontsize=6, color="0.35")

png = os.path.join(FIGD, "EDFig_percell_violin_v04.png")
pdf = os.path.join(FIGD, "EDFig_percell_violin_v04.pdf")
fig.savefig(png, dpi=300, bbox_inches="tight")
fig.savefig(pdf, bbox_inches="tight")
from PIL import Image
Image.MAX_IMAGE_PIXELS = None
print("PNG pixels:", Image.open(png).size)
print("saved:", png)
